### ISSUE TITLE
NPE in 10.0.0-INCAP

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/butterknife#2]
See https://github.com/JakeWharton/butterknife/pull/1230.

@tprochazka the issue has been addressed in version 10.0.0-INCAP-1. It will hit central in a few hours.
Can you confirm whether it works for you, please ?

**Comment by tprochazka** [comment]
Thanks!
Now it looks that it works on the demo project, it is just necessary to add this
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
But on a bigger project, there is still some issue. It fails at runtime because of the field which should be filled by Butterknife is empty I will try to reproduce it on the demo project. Currently, I just now that it happens when I'm using `bind(@NonNull View target)`

**Comment by stephanenicolas** [comment]
@tprochazka thx for testing the new artifact. Let's close this issue and open one with more details when you have some.

**Comment by tprochazka** [comment]
It was my fault, everything works correctly now. Thanks!

**Comment by stephanenicolas** [comment]
That's great. FYI, I am also gonna add Task Configuration Avoidance next week to this fork.
